apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
  namespace: crud-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/prempavuluri/workspace/infra/assignment-volume
